/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }) => {
  behaviors.skilldHelperGrid = {
    attach: (context) => {
      once("h-grid", ".h-grid", context).forEach((el) => {
        behaviors.skilldHelperGrid.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    }
  };
})(Drupal);
