/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
(({ behaviors }) => {
  behaviors.kaizerAtomText = {
    attach: (context) => {
      once('a-text', '.a-text', context).forEach((el) => {
        behaviors.kaizerAtomText.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    },
  };
})(Drupal);
