/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }, Splide) => {
  behaviors.skilldHSlider = {
    attach: (context) => {
      if (!Splide) {
        return;
      }
      once("h-slider", ".h-slider", context).forEach((el) => {
        const sliderEl = el.querySelector(".h-slider__slider");
        if (sliderEl) {
          if (el.classList.contains("h-slider--banner")) {
            behaviors.skilldHSlider.bannerSlider(el, sliderEl);
          }
          if (el.classList.contains("h-slider--cards")) {
            behaviors.skilldHSlider.cardsSlider(el, sliderEl);
          }
        }
      });
    },
    bannerSlider: (el, sliderEl) => {
      const slider = new Splide(sliderEl, {
        type: "loop",
        arrows: false,
        pagination: false
      });
      slider.mount();
    },
    cardsSlider: (el, sliderEl) => {
      const slider = new Splide(sliderEl, {
        type: "loop",
        arrows: false,
        pagination: false,
        perPage: 1,
        gap: 30,
        mediaQuery: "min",
        breakpoints: {
          769: {
            perPage: 2
          },
          1025: {
            perPage: 3
          }
        }
      });
      slider.mount();
    }
  };
})(Drupal, window.Splide);
