/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
import { c as controls, G as Glide } from "./vendor/vendor.glide.modular.esm.js";
/* empty css                           */(({ behaviors }, SlideScript, SliderControls) => {
  behaviors.caesarSlider = {
    attach: (context) => {
      Array.prototype.forEach.call(
        context.querySelectorAll(".o-slider"),
        (slider) => {
          new SlideScript(slider).mount({ SliderControls });
        }
      );
    }
  };
})(Drupal, Glide, controls);
