/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
(({ behaviors }) => {
  behaviors.kaizerMoleculeBanner = {
    attach: (context) => {
      once('m-banner', '.m-banner', context).forEach((el) => {
        behaviors.kaizerMoleculeBanner.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    },
  };
})(Drupal);
