/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }) => {
  behaviors.skilldMoleculeRadios = {
    attach: (context) => {
      once("m-radios", ".m-radios", context).forEach((el) => {
        behaviors.skilldMoleculeRadios.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    }
  };
})(Drupal);
