/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }) => {
  behaviors.skilldAtomRadio = {
    attach: (context) => {
      once("a-radio", ".a-radio", context).forEach((el) => {
        behaviors.skilldAtomRadio.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    }
  };
})(Drupal);
