/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }) => {
  behaviors.eshopgen_base_theme_storybook_a_radio = {
    defaultEntry: () => {
      return {
        className: "a-radio",
        processingName: "storybook-a-radio"
      };
    },
    customEntry: () => {
    },
    entries: () => {
      const entries = [
        behaviors.eshopgen_base_theme_storybook_a_radio.defaultEntry()
      ];
      if (behaviors.eshopgen_base_theme_storybook_a_radio.customEntry()) {
        entries.push(
          ...behaviors.eshopgen_base_theme_storybook_a_radio.customEntry()
        );
      }
      return entries;
    },
    attach: (context) => {
      behaviors.eshopgen_base_theme_storybook_a_radio.entries().forEach((entry) => {
        once(entry.processingName, `.${entry.className}`, context).forEach(
          (el) => {
            behaviors.eshopgen_base_theme_storybook_a_radio.handler({
              el,
              entry
            });
          }
        );
      });
    },
    handler: (obj) => {
      console.log(obj.el);
    }
  };
})(Drupal);
