/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
(({ behaviors }) => {
  behaviors.kaizerAtomButton = {
    attach: (context) => {
      once('a-button', '.a-button', context).forEach((el) => {
        behaviors.kaizerAtomButton.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    },
  };
})(Drupal);
