/**
 * DO NOT EDIT THIS FILE.
 * It's generated automatically by 'yarn build' command.
 * @preserve
 **/
(({ behaviors }) => {
  behaviors.kaizerTemplatePage = {
    attach: (context) => {
      once('t-page', '.t-page', context).forEach((el) => {
        behaviors.kaizerTemplatePage.handler(el);
      });
    },
    handler: (el) => {
      console.log(el);
    },
  };
})(Drupal);
