/**
  * DO NOT EDIT THIS FILE.
  * It's generated automatically by 'yarn build' command.
  * @preserve
**/
(({ behaviors }) => {
  behaviors.eshopgen_base_theme_storybook_m_details = {
    defaultEntry: () => {
      return {
        className: "m-details",
        processingName: "storybook-m-details"
      };
    },
    customEntry: () => {
    },
    entries: () => {
      const entries = [
        behaviors.eshopgen_base_theme_storybook_m_details.defaultEntry()
      ];
      if (behaviors.eshopgen_base_theme_storybook_m_details.customEntry()) {
        entries.push(
          ...behaviors.eshopgen_base_theme_storybook_m_details.customEntry()
        );
      }
      return entries;
    },
    attach: (context) => {
      behaviors.eshopgen_base_theme_storybook_m_details.entries().forEach((entry) => {
        once(entry.processingName, `.${entry.className}`, context).forEach(
          (el) => {
            behaviors.eshopgen_base_theme_storybook_m_details.handler({
              el,
              entry
            });
          }
        );
      });
    },
    handler: (obj) => {
      console.log(obj.el);
    }
  };
})(Drupal);
